# Generated by Django 3.0.3 on 2020-04-25 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200301_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='orgID',
            field=models.CharField(max_length=128, unique=False),
            preserve_default=False,
        ),
    ]
