# Generated by Django 3.0.3 on 2020-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_orgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgID',
            field=models.CharField(max_length=128),
        ),
    ]
